import express, {type NextFunction, type Request, type Response} from 'express';
import bcrypt from 'bcryptjs';
import crypto from 'node:crypto';
import path from 'node:path';
import fs from 'node:fs';
import type {DB} from './db.js';

const now=()=>new Date().toISOString(), hash=(s:string)=>crypto.createHash('sha256').update(s).digest('hex');
const token=()=>crypto.randomBytes(24).toString('base64url');
const remote=(value:string)=>{let s=value.trim().replace(/\\/g,'/').replace(/\.git\/?$/i,'').replace(/\/$/,'');const scp=s.match(/^(?:[^@/]+@)?([^:/]+):(.+)$/);if(scp&&!s.includes('://'))s=`${scp[1]}/${scp[2]}`;else {try{const u=new URL(s);s=`${u.hostname}${u.pathname}`}catch{}}return s.replace(/^\/+/,'').toLowerCase()};
type Authed=Request&{user?:any;agent?:any};
const body=(keys:string[])=>(req:Request,res:Response,next:NextFunction)=>{for(const k of keys)if(typeof req.body?.[k]!=='string'||!req.body[k].trim())return res.status(400).json({error:`${k} is required`});next()};
export function createApp(db:DB, webDir?:string){
 const app=express();app.use(express.json({limit:'512kb'}));
 const userAuth=(req:Authed,res:Response,next:NextFunction)=>{const t=req.headers.authorization?.replace(/^Bearer\s+/i,'');const row=t&&db.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=?').get(hash(t));if(!row)return res.status(401).json({error:'unauthorized'});req.user=row;next()};
 const agentAuth=(req:Authed,res:Response,next:NextFunction)=>{const t=req.headers.authorization?.replace(/^Bearer\s+/i,'');const row:any=t&&db.prepare('SELECT a.*,u.name user_name FROM agents a JOIN users u ON u.id=a.user_id WHERE a.token_hash=?').get(hash(t));if(!row)return res.status(401).json({error:'unauthorized agent'});req.agent=row;db.prepare('UPDATE agents SET last_seen=? WHERE id=?').run(now(),row.id);next()};
 const member=(uid:number,wid:number)=>db.prepare('SELECT 1 FROM workspace_members WHERE user_id=? AND workspace_id=?').get(uid,wid);
 app.get('/api/health',(_q,r)=>r.json({ok:true}));
 app.post('/api/auth/register',body(['name','email','password']),(req,res)=>{try{const info=db.prepare('INSERT INTO users(name,email,password_hash,created_at) VALUES(?,?,?,?)').run(req.body.name.trim(),req.body.email.trim().toLowerCase(),bcrypt.hashSync(req.body.password,10),now());const raw=token();db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(raw),info.lastInsertRowid,now());res.status(201).json({token:raw,user:{id:Number(info.lastInsertRowid),name:req.body.name,email:req.body.email.toLowerCase()}})}catch(e:any){res.status(409).json({error:'email already registered'})}});
 app.post('/api/auth/login',body(['email','password']),(req,res)=>{const u:any=db.prepare('SELECT * FROM users WHERE email=?').get(req.body.email.trim().toLowerCase());if(!u||!bcrypt.compareSync(req.body.password,u.password_hash))return res.status(401).json({error:'invalid credentials'});const raw=token();db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(raw),u.id,now());res.json({token:raw,user:{id:u.id,name:u.name,email:u.email}})});
 app.post('/api/auth/logout',userAuth,(req:Authed,res)=>{const t=req.headers.authorization!.replace(/^Bearer\s+/i,'');db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash(t));res.status(204).end()});
 app.get('/api/auth/me',userAuth,(req:Authed,res)=>res.json({id:req.user.id,name:req.user.name,email:req.user.email}));
 app.post('/api/workspaces',userAuth,body(['name']),(req:Authed,res)=>{const code=crypto.randomBytes(5).toString('hex').toUpperCase();const id=Number(db.transaction(()=>{const i=db.prepare('INSERT INTO workspaces(name,owner_id,invite_code,created_at) VALUES(?,?,?,?)').run(req.body.name.trim(),req.user.id,code,now());db.prepare("INSERT INTO workspace_members VALUES(?,?,'owner')").run(i.lastInsertRowid,req.user.id);return i.lastInsertRowid})());res.status(201).json({id,name:req.body.name,inviteCode:code})});
 app.post('/api/workspaces/join',userAuth,body(['inviteCode']),(req:Authed,res)=>{const w:any=db.prepare('SELECT * FROM workspaces WHERE invite_code=?').get(req.body.inviteCode.trim().toUpperCase());if(!w)return res.status(404).json({error:'invalid invite code'});db.prepare("INSERT OR IGNORE INTO workspace_members VALUES(?,?,'member')").run(w.id,req.user.id);res.json(w)});
 app.get('/api/workspaces',userAuth,(req:Authed,res)=>res.json(db.prepare('SELECT w.*,wm.role FROM workspaces w JOIN workspace_members wm ON wm.workspace_id=w.id WHERE wm.user_id=? ORDER BY w.id').all(req.user.id)));
 app.get('/api/workspaces/:id/members',userAuth,(req:Authed,res)=>{if(!member(req.user.id,+req.params.id))return res.status(403).json({error:'forbidden'});res.json(db.prepare('SELECT u.id,u.name,u.email,wm.role FROM workspace_members wm JOIN users u ON u.id=wm.user_id WHERE wm.workspace_id=?').all(req.params.id))});
 app.post('/api/agents/register',userAuth,body(['machineName']),(req:Authed,res)=>{const raw=token();const i=db.prepare('INSERT INTO agents(user_id,machine_name,token_hash,last_seen,created_at) VALUES(?,?,?,?,?)').run(req.user.id,req.body.machineName,hash(raw),now(),now());res.status(201).json({agentId:Number(i.lastInsertRowid),token:raw})});
 app.get('/api/agents/status',agentAuth,(req:Authed,res)=>res.json({id:req.agent.id,userId:req.agent.user_id,machineName:req.agent.machine_name,lastSeen:req.agent.last_seen}));
 app.post('/api/agents/heartbeat',agentAuth,(_q,res)=>res.json({ok:true,at:now()}));
 app.post('/api/repositories/register',agentAuth,body(['workspaceId','name','remoteUrl','localKey']),(req:Authed,res)=>{const wid=+req.body.workspaceId;if(!member(req.agent.user_id,wid))return res.status(403).json({error:'forbidden'});const norm=remote(req.body.remoteUrl);if(!norm)return res.status(400).json({error:'remote URL required'});db.prepare('INSERT OR IGNORE INTO repositories(workspace_id,name,remote_url,normalized_remote,created_at) VALUES(?,?,?,?,?)').run(wid,req.body.name,req.body.remoteUrl,norm,now());const repo:any=db.prepare('SELECT * FROM repositories WHERE workspace_id=? AND normalized_remote=?').get(wid,norm);db.prepare('INSERT INTO local_clones(agent_id,repository_id,local_key,branch,last_seen) VALUES(?,?,?,?,?) ON CONFLICT(agent_id,local_key) DO UPDATE SET repository_id=excluded.repository_id,branch=excluded.branch,last_seen=excluded.last_seen').run(req.agent.id,repo.id,req.body.localKey,req.body.branch||null,now());res.json(repo)});
 app.get('/api/workspaces/:id/repositories',userAuth,(req:Authed,res)=>{if(!member(req.user.id,+req.params.id))return res.status(403).json({error:'forbidden'});res.json(db.prepare('SELECT r.*,COUNT(DISTINCT lc.agent_id) clone_count FROM repositories r LEFT JOIN local_clones lc ON lc.repository_id=r.id WHERE r.workspace_id=? GROUP BY r.id').all(req.params.id))});
 app.post('/api/activity',agentAuth,body(['eventKey','type','occurredAt']),(req:Authed,res)=>{const repositoryId=Number(req.body.repositoryId);if(!Number.isInteger(repositoryId)||repositoryId<1)return res.status(400).json({error:'repositoryId is required'});const repo:any=db.prepare('SELECT r.* FROM repositories r JOIN workspace_members wm ON wm.workspace_id=r.workspace_id WHERE r.id=? AND wm.user_id=?').get(repositoryId,req.agent.user_id);if(!repo)return res.status(403).json({error:'repository not available'});const info=db.prepare('INSERT OR IGNORE INTO activity_events(event_key,user_id,agent_id,repository_id,type,occurred_at,data,created_at) VALUES(?,?,?,?,?,?,?,?)').run(req.body.eventKey,req.agent.user_id,req.agent.id,repo.id,req.body.type,req.body.occurredAt,JSON.stringify(req.body.data||{}),now());res.status(info.changes?201:200).json({accepted:!!info.changes})});
 const queryActivity=(req:Authed,res:Response,extra:string,args:any[])=>{const wid=Number(req.params.workspaceId||req.query.workspaceId||0);if(!wid||!member(req.user!.id,wid))return res.status(403).json({error:'forbidden'});let sql='SELECT e.*,u.name user_name,r.name repository_name FROM activity_events e JOIN users u ON u.id=e.user_id JOIN repositories r ON r.id=e.repository_id WHERE r.workspace_id=?';const vals:any[]=[wid,...args];sql+=extra;if(req.query.from){sql+=' AND e.occurred_at>=?';vals.push(String(req.query.from))}if(req.query.to){sql+=' AND e.occurred_at<=?';vals.push(String(req.query.to)+'T23:59:59.999Z')}sql+=' ORDER BY e.occurred_at DESC LIMIT 500';res.json(db.prepare(sql).all(...vals).map((x:any)=>({...x,data:JSON.parse(x.data)})))};
 app.get('/api/workspaces/:workspaceId/activity',userAuth,(q:Authed,r)=>queryActivity(q,r,'',[]));app.get('/api/repositories/:id/activity',userAuth,(q:Authed,r)=>queryActivity(q,r,' AND e.repository_id=?',[+q.params.id]));app.get('/api/users/:id/activity',userAuth,(q:Authed,r)=>queryActivity(q,r,' AND e.user_id=?',[+q.params.id]));
 app.post('/api/reports/jobs',userAuth,body(['workspaceId','startDate','endDate','reporter']),(req:Authed,res)=>{const wid=+req.body.workspaceId;if(!member(req.user.id,wid))return res.status(403).json({error:'forbidden'});if(!['codex','hermes'].includes(req.body.reporter))return res.status(400).json({error:'invalid reporter'});const i=db.prepare("INSERT INTO report_jobs(workspace_id,user_id,reporter,start_date,end_date,status,created_at) VALUES(?,?,?,?,?,'pending',?)").run(wid,req.user.id,req.body.reporter,req.body.startDate,req.body.endDate,now());res.status(201).json({id:Number(i.lastInsertRowid),status:'pending'})});
 app.get('/api/reports/jobs/:id',userAuth,(req:Authed,res)=>{const j:any=db.prepare('SELECT * FROM report_jobs WHERE id=? AND user_id=?').get(req.params.id,req.user.id);if(!j)return res.status(404).json({error:'not found'});res.json(j)});
 app.get('/api/agents/jobs',agentAuth,(req:Authed,res)=>res.json(db.prepare("SELECT * FROM report_jobs WHERE user_id=? AND status='pending' ORDER BY id LIMIT 1").all(req.agent.user_id)));
 app.post('/api/agents/jobs/:id/claim',agentAuth,(req:Authed,res)=>{const i=db.prepare("UPDATE report_jobs SET status='running',agent_id=?,claimed_at=? WHERE id=? AND user_id=? AND status='pending'").run(req.agent.id,now(),req.params.id,req.agent.user_id);if(!i.changes)return res.status(409).json({error:'job unavailable'});res.json(db.prepare('SELECT * FROM report_jobs WHERE id=?').get(req.params.id))});
 app.get('/api/agents/jobs/:id/context',agentAuth,(req:Authed,res)=>{const j:any=db.prepare('SELECT * FROM report_jobs WHERE id=? AND user_id=?').get(req.params.id,req.agent.user_id);if(!j)return res.status(404).json({error:'not found'});const events=db.prepare('SELECT e.*,r.name repository_name,r.normalized_remote FROM activity_events e JOIN repositories r ON r.id=e.repository_id WHERE e.user_id=? AND r.workspace_id=? AND e.occurred_at>=? AND e.occurred_at<=? ORDER BY e.occurred_at').all(j.user_id,j.workspace_id,j.start_date,j.end_date+'T23:59:59.999Z').map((x:any)=>({...x,data:JSON.parse(x.data)}));res.json({job:j,events})});
 app.post('/api/agents/jobs/:id/complete',agentAuth,body(['markdown']),(req:Authed,res)=>{const j:any=db.prepare("SELECT * FROM report_jobs WHERE id=? AND user_id=? AND status='running' AND agent_id=?").get(req.params.id,req.agent.user_id,req.agent.id);if(!j)return res.status(409).json({error:'job not claimed'});db.transaction(()=>{db.prepare('INSERT INTO reports(job_id,workspace_id,user_id,start_date,end_date,markdown,created_at) VALUES(?,?,?,?,?,?,?)').run(j.id,j.workspace_id,j.user_id,j.start_date,j.end_date,req.body.markdown,now());db.prepare("UPDATE report_jobs SET status='completed',completed_at=? WHERE id=?").run(now(),j.id)})();res.status(201).json({ok:true})});
 app.post('/api/agents/jobs/:id/fail',agentAuth,body(['error']),(req:Authed,res)=>{const i=db.prepare("UPDATE report_jobs SET status='failed',error=?,completed_at=? WHERE id=? AND user_id=? AND agent_id=? AND status='running'").run(req.body.error,now(),req.params.id,req.agent.user_id,req.agent.id);res.status(i.changes?200:409).json({ok:!!i.changes})});
 app.get('/api/workspaces/:id/reports',userAuth,(req:Authed,res)=>{if(!member(req.user.id,+req.params.id))return res.status(403).json({error:'forbidden'});res.json(db.prepare('SELECT r.*,u.name user_name FROM reports r JOIN users u ON u.id=r.user_id WHERE workspace_id=? ORDER BY created_at DESC').all(req.params.id))});
 app.get('/api/reports/:id',userAuth,(req:Authed,res)=>{const x:any=db.prepare('SELECT r.* FROM reports r JOIN workspace_members wm ON wm.workspace_id=r.workspace_id WHERE r.id=? AND wm.user_id=?').get(req.params.id,req.user.id);if(!x)return res.status(404).json({error:'not found'});res.json(x)});
 if(webDir&&fs.existsSync(webDir)){app.use(express.static(webDir));app.use((q,r,next)=>{if(q.method!=='GET')return next();if(q.path.startsWith('/api/'))return r.status(404).json({error:'not found'});r.sendFile(path.join(webDir,'index.html'))})}
 app.use((e:any,_q:Request,r:Response,_n:NextFunction)=>{console.error(e);r.status(500).json({error:'internal error'})});return app;
}
export {remote as normalizeRemote};
