import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';
export const git=(repo:string,args:string[])=>execFileSync('git',['-C',repo,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
export function discover(root:string){const found:string[]=[];const walk=(dir:string)=>{let entries:fs.Dirent[];try{entries=fs.readdirSync(dir,{withFileTypes:true})}catch{return}if(entries.some(e=>e.name==='.git')){found.push(dir);return}for(const e of entries)if(e.isDirectory()&&!e.isSymbolicLink()&&!['node_modules','.cache'].includes(e.name))walk(path.join(dir,e.name))};walk(path.resolve(root));return found}
export function normalizeRemote(value:string){let s=value.trim().replace(/\\/g,'/').replace(/\.git\/?$/i,'').replace(/\/$/,'');const m=s.match(/^(?:[^@/]+@)?([^:/]+):(.+)$/);if(m&&!s.includes('://'))s=`${m[1]}/${m[2]}`;else try{const u=new URL(s);s=`${u.hostname}${u.pathname}`}catch{}return s.replace(/^\/+/,'').toLowerCase()}
export function inspectRepo(repo:string){const url=git(repo,['remote','get-url','origin']);return {path:path.resolve(repo),name:path.basename(repo),remoteUrl:url,normalizedRemote:normalizeRemote(url),branch:git(repo,['branch','--show-current'])||'(detached)'}}
export function commitData(repo:string){const raw=git(repo,['show','-s','--format=%H%n%s%n%aI%n%an%n%ae','HEAD']).split('\n');const stat=git(repo,['show','--format=','--numstat','HEAD']).split('\n').filter(Boolean);return {commitSha:raw[0],message:raw[1],commitTimestamp:raw[2],authorName:raw[3],authorEmail:raw[4],branch:git(repo,['branch','--show-current'])||'(detached)',filesChanged:stat.length,insertions:stat.reduce((n,x)=>n+(parseInt(x.split('\t')[0])||0),0),deletions:stat.reduce((n,x)=>n+(parseInt(x.split('\t')[1])||0),0),changedFiles:stat.map(x=>x.split('\t').slice(2).join('\t'))}}
export function stagedData(repo:string){const lines=git(repo,['diff','--cached','--numstat']).split('\n').filter(Boolean);return {branch:git(repo,['branch','--show-current'])||'(detached)',filesChanged:lines.length,insertions:lines.reduce((n,x)=>n+(parseInt(x.split('\t')[0])||0),0),deletions:lines.reduce((n,x)=>n+(parseInt(x.split('\t')[1])||0),0),changedFiles:lines.map(x=>x.split('\t').slice(2).join('\t'))}}
const hooks=['post-commit','post-checkout','post-merge','post-rewrite','pre-push'];
export function installHooks(repo:string){const hooksDir=git(repo,['rev-parse','--git-path','hooks']);const absolute=path.isAbsolute(hooksDir)?hooksDir:path.join(repo,hooksDir);fs.mkdirSync(absolute,{recursive:true});for(const h of hooks){const target=path.join(absolute,h), original=target+'.tracemini-original';if(fs.existsSync(target)&&!fs.readFileSync(target,'utf8').includes('TraceMini managed hook')){if(!fs.existsSync(original))fs.renameSync(target,original)}const type=h==='post-commit'?'commit':h==='post-checkout'?'branch':h==='post-merge'?'merge':h==='post-rewrite'?'rewrite':'push';const script=`#!/bin/sh\n# TraceMini managed hook\noriginal="$0.tracemini-original"\nif [ -x "$original" ]; then "$original" "$@" || exit $?; fi\ncommand -v tracemini >/dev/null 2>&1 && tracemini event --repo "$(git rev-parse --show-toplevel)" --type ${type} --hook ${h} "$@" >/dev/null 2>&1 || true\nexit 0\n`;fs.writeFileSync(target,script,{mode:0o755})}return hooks}
