#!/usr/bin/env node
import os from 'node:os';import path from 'node:path';import {api} from './api.js';import {loadConfig,saveConfig,loadQueue,saveQueue,eventKey} from './config.js';import {discover,inspectRepo,installHooks,commitData,stagedData,git} from './git.js';import {flush,runAgent} from './agent.js';
const args=process.argv.slice(2),cmd=args.shift(),flag=(n:string)=>{const i=args.indexOf(n);return i>=0?args[i+1]:undefined};const c=loadConfig();
async function main(){
 if(cmd==='login'){const server=flag('--server');if(server)c.serverUrl=server;const bearer=flag('--token');if(!bearer)throw new Error('login requires --token <user bearer token>');c.userToken=bearer;const a=await api<any>(c,'/api/agents/register',{method:'POST',body:JSON.stringify({machineName:flag('--machine')||os.hostname()})},false);c.agentToken=a.token;c.agentId=a.agentId;saveConfig(c);console.log(`Agent ${a.agentId} registered`);return}
 if(cmd==='join'){if(!args[0])throw new Error('join requires invite code');const w=await api<any>(c,'/api/workspaces/join',{method:'POST',body:JSON.stringify({inviteCode:args[0]})},false);c.workspaceId=w.id;saveConfig(c);console.log(`Joined ${w.name} (${w.id})`);return}
 if(cmd==='use-workspace'){c.workspaceId=+args[0];saveConfig(c);console.log(`Workspace ${c.workspaceId} selected`);return}
 if(cmd==='watch'){if(!c.workspaceId)throw new Error('select a workspace with join or use-workspace');const root=path.resolve(args[0]||'');if(!c.watchedPaths.includes(root))c.watchedPaths.push(root);for(const repoPath of discover(root)){let info;try{info=inspectRepo(repoPath)}catch{console.warn(`Skipping ${repoPath}: origin remote required`);continue}const repo=await api<any>(c,'/api/repositories/register',{method:'POST',body:JSON.stringify({workspaceId:String(c.workspaceId),name:info.name,remoteUrl:info.remoteUrl,localKey:info.path,branch:info.branch})});const clone={path:info.path,repositoryId:repo.id,normalizedRemote:repo.normalized_remote,name:repo.name};c.clones=c.clones.filter(x=>x.path!==info.path);c.clones.push(clone);installHooks(info.path);console.log(`Watching ${info.path} -> ${repo.name} #${repo.id}`)}saveConfig(c);return}
 if(cmd==='repositories'){console.table(c.clones);return}
 if(cmd==='status'){const status=await api<any>(c,'/api/agents/status');console.log(JSON.stringify({...status,server:c.serverUrl,workspaceId:c.workspaceId,watchedPaths:c.watchedPaths,clones:c.clones.length,queued:loadQueue().length},null,2));return}
 if(cmd==='event'){const repoPath=path.resolve(flag('--repo')||process.cwd()),type=flag('--type')||args[0];const clone=c.clones.find(x=>x.path===repoPath);if(!clone)throw new Error(`repository is not registered: ${repoPath}`);let data:any={branch:git(repoPath,['branch','--show-current'])||'(detached)',hook:flag('--hook')};if(type==='commit')data=commitData(repoPath);else if(type==='stage')data=stagedData(repoPath);else if(type==='branch')data={...data,oldCommit:args.at(-3),newCommit:args.at(-2),branchCheckout:args.at(-1)};else if(type==='merge'||type==='pull')data={...data,commitSha:git(repoPath,['rev-parse','HEAD'])};else if(type==='push')data={...data,remote:args.at(-2),remoteUrl:args.at(-1),observable:type==='push'&&flag('--hook')==='pre-push'?'attempt':'explicit'};const occurredAt=new Date().toISOString(),key=eventKey([type,clone.repositoryId,data.commitSha||'',data.oldCommit||'',data.newCommit||'',occurredAt.slice(0,16),data]);const q=loadQueue();q.push({eventKey:key,repositoryId:clone.repositoryId,type,occurredAt,data,attempts:0,nextAttempt:0});saveQueue(q);await flush(c);return}
 if(cmd==='start'||cmd==='once'){await runAgent(c,cmd==='once');return}
 console.log('Usage: tracemini login --server URL --token USER_TOKEN | join CODE | use-workspace ID | watch PATH | repositories | status | event --repo PATH --type TYPE | start | once')
}
main().catch(e=>{console.error(`TraceMini: ${e.message||e}`);process.exitCode=1});
